# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-Keyczar
version:      0.03
version_from: lib/Crypt/Keyczar.pm
installdirs:  site
requires:
    JSON:                          0
    MIME::Base64:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
